name: PyTest
on: [push, workflow_dispatch]

jobs:
  test:
    name: Test python scripts
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python dependencies
        run: |
          sudo apt install -y mupdf-tools poppler-utils
          #my code
          #sudo apt-get install texlive-latex-recommended 
          python3 -m pip install --upgrade pip
          pip3 install pytest pytest-cov pytest-github-actions-annotate-failures jupyter numpy matplotlib pytest-mpl
      - name: Test with pytest
        run: |
          # My code
          jupyter nbconvert --to script --output "jupyter_assignment_dirty" jupyter_assignment.ipynb
          echo "step 1"
          jupyter nbconvert --to script --output "matplotlib_assignment_dirty" matplotlib_assignment.ipynb
          echo "step 2"
          cat jupyter_assignment_dirty.py | grep -v "^#" | grep -v "^$" | grep -v "get_ipython()" | grep -vE "(\s|=|^)input\(" > jupyter_assignment.py
          echo "step 3"
          cat matplotlib_assignment_dirty.py | grep -v "^#" | grep -v "^$" | grep -v "get_ipython()" | grep -vE "(\s|=|^)input\(" > matplotlib_assignment.py
          cat matplotlib_assignment.py
          echo "step 4"
          pytest -s jupyter_tests.py
          echo "step 5"
          #Dont my code
          #jupyter nbconvert --to script --output "jupyter_assignment_dirty" jupyter_assignment.ipynb
          #jupyter nbconvert --to script matplotlib_assignment.ipynb
          #cat jupyter_assignment_dirty.py | grep -v "^#" | grep -v "^$" | grep -v "get_ipython()" | grep -vE "(\s|=|^)input\(" > jupyter_assignment.py
          #pytest -s jupyter_tests.py
          # My code
     # - name: Test with pytest1
     #   run: |
      #    pytest --mpl-generate-path=baseline Create_img_3.py
      #- name: Test with pytest2
       # run: |
       #   pytest --mpl Add_img_13.py
